esphome:
  name: anavi_miracle_controller
  platform: ESP8266
  board: esp12e

wifi:
  ssid: "SET-YOUR-WIFI"
  password: "SET-YOUR-WIFI-PASSWORD"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Anavi Miracle Controller"
    password: "yhr8PZ0rwFUC"

captive_portal:

# Enable logging
logger:

# When no client connects to the native API within 5 minutes a
# watchdog kicks in and reboots the device. Therefore by default
# the Home Assistant API is disabled. Enabled it only if you will
# use it.

api:
  password: "opensource"

ota:
  password: "opensource"

# Please note that if an I2C sensor module is not attached ESPHome
# will report an error and the status LED will be blinking rapidly.
# To avoid this case either disable the status LED or any I2C
# sensor module that you don't plan to attach.
status_led:
  pin: GPIO16

light:
  - platform: fastled_clockless
    chipset: WS2812B
    rgb_order: GRB
    pin: GPIO12
    num_leds: 10
    name: "LED1"
    effects:
      - addressable_rainbow:
      - addressable_rainbow:
          name: Rainbow Effect With Custom Values
          speed: 10
          width: 50
      - addressable_color_wipe:
      - addressable_color_wipe:
          name: Color Wipe Effect With Custom Values
          colors:
            - red: 100%
              green: 100%
              blue: 100%
              num_leds: 1
            - red: 0%
              green: 0%
              blue: 0%
              num_leds: 1
          add_led_interval: 100ms
          reverse: False

  - platform: fastled_clockless
    chipset: WS2812B
    rgb_order: GRB
    pin: GPIO14
    num_leds: 10
    name: "LED2"
    effects:
      - addressable_rainbow:
      - addressable_rainbow:
          name: Rainbow Effect With Custom Values
          speed: 10
          width: 50
      - addressable_color_wipe:
      - addressable_color_wipe:
          name: Color Wipe Effect With Custom Values
          colors:
            - red: 100%
              green: 100%
              blue: 100%
              num_leds: 1
            - red: 0%
              green: 0%
              blue: 0%
              num_leds: 1
          add_led_interval: 100ms
          reverse: False

i2c:
  sda: GPIO4
  scl: GPIO5
  scan: False

font:
  - file: 'arial.ttf'
    id: font1
    size: 12

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    lambda: |-
      it.print(0, 0, id(font1), "ANAVI");
      it.print(0, 15, id(font1), "Miracle");
      it.print(0, 27, id(font1), "Controller");

#apds9960:
#  address: 0x39
#  update_interval: 60s

# There are some known ESPHome issue with DHT22 therefore the
# model has been explicitly configured. For more details have a
# look at the notes in the documentation and the reported issues:
# https://github.com/esphome/issues/issues/792
# https://esphome.io/components/sensor/dht.html

sensor:
  - platform: bh1750
    name: "BH1750 Illuminance"
    address: 0x23
    measurement_time: 69
    update_interval: 5s

  - platform: bmp085
    temperature:
      name: "BMP180 Temperature"
    pressure:
      name: "BMP180 Pressure"
    update_interval: 10s

# By default HTU21D I2C sensor module is disabled because it is
# not included in any of the kits of ANAVI Miracle Controller.

#  - platform: htu21d
#    temperature:
#      name: "HTU21D Temperature"
#    humidity:
#      name: "HTU21D Humidity"
#    update_interval: 10s

# There are known "ESP8266 Various Connection Issues" when
# the binary sensor is enabled. It affects ANAVI Miracle Controller
# therefore by default apds9960 is disabled:
# https://github.com/esphome/issues/issues/455
# However, below is an example how to enabled it if needed:

#  - platform: apds9960
#    type: CLEAR
#    name: "APDS9960 Clear Channel"

#binary_sensor:
#  - platform: apds9960
#    direction: UP
#    name: "APDS960 Up Movement"
